  $(document).ready(function() {
    $("#1").keyup(function() {
      var url = "https://en.wikipedia.org/w/api.php?action=opensearch&format=json&callback=?&search=" + $("#1").val();
      $.getJSON(url, function(data) {
        $("#4").attr("href", data[3][0]);
        $("#5").text(data[1][0]);
        $("#6").attr("href", data[3][1]);
        $("#7").text(data[1][1]);
        $("#8").attr("href", data[3][2]);
        $("#9").text(data[1][2]);
        $("#10").attr("href", data[3][3]);
        $("#11").text(data[1][3]);
        $("#12").attr("href", data[3][4]);
        $("#13").text(data[1][4]);
        $("#14").attr("href", data[3][5]);
        $("#15").text(data[1][5]);
        $("#16").attr("href", data[3][6]);
        $("#17").text(data[1][6]);
        $("#18").attr("href", data[3][7]);
        $("#19").text(data[1][7]);
        $("#20").attr("href", data[3][8]);
        $("#21").text(data[1][8]);
        $("#22").attr("href", data[3][9]);
        $("#23").text(data[1][9]);
        $("#24").attr("href", data[3][0]);
        $("#25").html("<hr>" + data[1][0]);
        $("#26").html(data[2][0] + "<hr>");
        $("#27").attr("href", data[3][1]);
        $("#28").html("<hr>" + data[1][1]);
        $("#29").html(data[2][1] + "<hr>");
        $("#30").attr("href", data[3][2]);
        $("#31").html("<hr>" + data[1][2]);
        $("#32").html(data[2][2] + "<hr>");
        $("#33").attr("href", data[3][3]);
        $("#34").html("<hr>" + data[1][3]);
        $("#35").html(data[2][3] + "<hr>");
        $("#36").attr("href", data[3][4]);
        $("#37").html("<hr>" + data[1][4]);
        $("#38").html(data[2][4] + "<hr>");
        $("#39").attr("href", data[3][5]);
        $("#40").html("<hr>" + data[1][5]);
        $("#41").html(data[2][5] + "<hr>");
        $("#42").attr("href", data[3][6]);
        $("#43").html("<hr>" + data[1][6]);
        $("#44").html(data[2][6] + "<hr>");
        $("#45").attr("href", data[3][7]);
        $("#46").html("<hr>" + data[1][7]);
        $("#47").html(data[2][7] + "<hr>");
        $("#48").attr("href", data[3][8]);
        $("#49").html("<hr>" + data[1][8]);
        $("#50").html(data[2][8] + "<hr>");
        $("#51").attr("href", data[3][9]);
        $("#52").html("<hr>" + data[1][9]);
        $("#53").html(data[2][9] + "<hr>");
      });
    });
  });